### ISSUE TITLE
Enable usage of PopOver as a widget

### ISSUE THREAD

**Issue by slimyjimmy** [minikin/popover#40]
Thanks for your work first of all.

If I'm not mistaken, we can currently, only use the `showPopover()` method to show a Popover. 
It would be really nice, however, if there was a Popover widget we could use in our build methods.

The reason I'm asking for this is, that I would like to create a size-aware widget that would render a Scaffold on smaller devices and a Popover on larger devices. Currently, I'd have to make the differentiation in the onTap() method but I'd prefer to do it in my SizeAwarePopover widget's build method.

**Comment by minikin** [comment]
@slimyjimmy Thank you for your request!
Unfortunately, I don't think the best direction to move. Because we want to have the following behavior:

>A popover is a transient view that appears above other content onscreen when you tap a control or in an area. Typically, a popover includes an arrow pointing to the location from which it emerged. Popovers can be nonmodal or modal. A nonmodal popover is dismissed by tapping another part of the screen or a button on the popover. A modal popover is dismissed by tapping a Cancel or other button on the popover.

Previously we had an implementation of Popover as a Widget. Then we decided to move in a direction which Flutter's modal dialogs have e.g  [showCupertino](https://pub.dev/documentation/card_settings/latest/helpers_platform_functions/showCupertino.html), to be more aligned with Flutter API.

So, the answer is: we're not going to implement Popover as Widget soon. However, feel free to fork this repos and do whatever you want with it 🤓
